<?xml version="1.0" encoding="utf-8"?><Database Name="LPHYSIC" Class="LPhyDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=LPHYSIC;User ID=sa" SettingsObjectName="LPhysical.Properties.Settings" SettingsPropertyName="LPHYSICConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DERAL10" Member="DERAL10s">
    <Type Name="DERAL10">
      <Column Name="QID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CONTENT" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CTLDUNG" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CTL1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CTL2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CTL3" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DERAL11" Member="DERAL11s">
    <Type Name="DERAL11">
      <Column Name="QID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CONTENT" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CTLDUNG" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CTL1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CTL2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CTL3" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DERAL12" Member="DERAL12s">
    <Type Name="DERAL12">
      <Column Name="QID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CONTENT" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CTLDUNG" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CTL1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CTL2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CTL3" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ELEVEN" Member="ELEVENs">
    <Type Name="ELEVEN">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BAI" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CONTENT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TENBASE" Member="TENBASEs">
    <Type Name="TENBASE">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BAI" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CONTENT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TWENTH" Member="TWENTHs">
    <Type Name="TWENTH">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BAI" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CONTENT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>