CREATE DATABASE QUESTION
GO
USE QUESTION
GO
CREATE TABLE DERAL10(
QID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CONTENT NVARCHAR(200) NOT NULL,
CTLDUNG NVARCHAR(200) NOT NULL,
CTL1 NVARCHAR(200),
CTL2 NVARCHAR(200),
CTL3 NVARCHAR(200)
)
GO
CREATE TABLE DERAL11(
QID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CONTENT NVARCHAR(200) NOT NULL,
CTLDUNG NVARCHAR(200) NOT NULL,
CTL1 NVARCHAR(200),
CTL2 NVARCHAR(200),
CTL3 NVARCHAR(200)
)
GO
CREATE TABLE DERAL12(
QID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CONTENT NVARCHAR(200) NOT NULL,
CTLDUNG NVARCHAR(200) NOT NULL,
CTL1 NVARCHAR(200),
CTL2 NVARCHAR(200),
CTL3 NVARCHAR(200)
)

GO
INSERT INTO DERAL12 VALUES(N'Chọn câu sai? Tần số dao động tuần hoàn là:',N'Số dao động thực hiện được trong 1 phút,',
N'Số chu kì thực hiện được trong một giây',N'Số lần trạng thái dao động lặp lại trong 1 đơn vị thời gian',N'Số lần li độ dao động lặp lại như cũ trong 1 đơn vị thời gian'
)
INSERT INTO DERAL12 VALUES (
N'Đại lượng nào sau đây không cho biết dao động điều hòa là nhanh hay chậm',
N'Biên độ',
N'Chu kì',
N'Tần số',
N'Tốc độ góc'
)
GO
SELECT * FROM DERAL10
SELECT * FROM DERAL11
SELECT * FROM DERAL12
DROP TABLE DERAL10